# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakelab" do
  version "0.0.4"

  on_macos do
    on_arm do
      sha256 "56cee3b7eef821f14601ebb63ab1c49e2ac63c24ceb4baef250bff9e072bdd72"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "db01d371943599b0db980b5704a97a6663cee5ea58d58aeb45b3696a6c578bf5"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c0ac73ca2489cb316b636ff1da4306250960a3cc00af6ce9293d5b61e57371a"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "d5d3763422d81415130c344213736d48a2cdb955ab8e6c8d36d3cc60121d8d12"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wakelab"
  desc "Wake and sleep your whole homelab from the CLI"
  homepage "https://github.com/DiegoHeer/wakelab"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wake"
  bash_completion "completions/wake.bash"
  fish_completion "completions/wake.fish"
  zsh_completion "completions/_wake"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wake"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run this once to enable tab completion in your shell:
      wake completion install
  EOS
end
