# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakelab" do
  version "0.0.6"

  on_macos do
    on_arm do
      sha256 "5b9b73d9d17a7a212e2e0566788d0a3cb1a228036ca481aa96e2ebd406036b47"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "443eeb619729a1dec1941db11f439392ea9c71040ff75a0e636b3bfb431d0605"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "148041505a751b070df3cda61a8490cac4b701e07edfb01074355d054c4c090d"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1075b24f4ba254e39bfba4e2bf8c491ddeae8f8a6c91b25fad240f04038541db"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wakelab"
  desc "Wake and sleep your whole homelab from the CLI"
  homepage "https://github.com/DiegoHeer/wakelab"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wake"
  bash_completion "completions/wake.bash"
  fish_completion "completions/wake.fish"
  zsh_completion "completions/_wake"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wake"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run this once to enable tab completion in your shell:
      wake completion install
  EOS
end
