# This file was generated by GoReleaser. DO NOT EDIT.
cask "wakelab" do
  version "0.0.5"

  on_macos do
    on_arm do
      sha256 "3e1ad39f39241d1657377e4742c3951d24e3bd8a35f2572f4a983719fcb9081d"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b8f7faf68c18e2b4ebc159c1eb9ef386fb1a1f4b27ecfc21d992a6039309b833"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "21e42167666f6f36d0727d84a2a3b6824fb619acc7a82edb2f4626b2ea8104b7"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1a4d43c05ee26e1f561543e8640f7fe1520fb1812aaeac0727b1698d6cbb78f9"
      url "https://github.com/DiegoHeer/wakelab/releases/download/v#{version}/wakelab_#{version}_linux_amd64.tar.gz"
    end
  end

  name "wakelab"
  desc "Wake and sleep your whole homelab from the CLI"
  homepage "https://github.com/DiegoHeer/wakelab"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wake"
  bash_completion "completions/wake.bash"
  fish_completion "completions/wake.fish"
  zsh_completion "completions/_wake"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wake"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run this once to enable tab completion in your shell:
      wake completion install
  EOS
end
