# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wakelab < Formula
  desc "Wake and sleep your whole homelab from the CLI"
  homepage "https://github.com/DiegoHeer/wakelab"
  version "0.0.1"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DiegoHeer/wakelab/releases/download/v0.0.1/wakelab_0.0.1_darwin_amd64.tar.gz"
      sha256 "0ed709d743aa678bee05b485c3d72fe811ee73b5f41b006e6a26203e949f21c7"

      define_method(:install) do
        bin.install "wake"
        bash_completion.install "completions/wake.bash" => "wake"
        zsh_completion.install "completions/_wake"
        fish_completion.install "completions/wake.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DiegoHeer/wakelab/releases/download/v0.0.1/wakelab_0.0.1_darwin_arm64.tar.gz"
      sha256 "ee57242da17543b3e245d12f41fd259b93981591adb512a33eb3a49bdac173fb"

      define_method(:install) do
        bin.install "wake"
        bash_completion.install "completions/wake.bash" => "wake"
        zsh_completion.install "completions/_wake"
        fish_completion.install "completions/wake.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DiegoHeer/wakelab/releases/download/v0.0.1/wakelab_0.0.1_linux_amd64.tar.gz"
      sha256 "70ef1eb4de23bbb4440bac65dec59c4e096bd5682e09bbaf699050f3c5a565a4"
      define_method(:install) do
        bin.install "wake"
        bash_completion.install "completions/wake.bash" => "wake"
        zsh_completion.install "completions/_wake"
        fish_completion.install "completions/wake.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DiegoHeer/wakelab/releases/download/v0.0.1/wakelab_0.0.1_linux_arm64.tar.gz"
      sha256 "68d93d508202ead889d5f74d7dd01ff7dfd1e1903741c3d45d2ba0c43f278fcc"
      define_method(:install) do
        bin.install "wake"
        bash_completion.install "completions/wake.bash" => "wake"
        zsh_completion.install "completions/_wake"
        fish_completion.install "completions/wake.fish"
      end
    end
  end

  test do
    assert_match "wake version", shell_output("#{bin}/wake --version")
  end
end
