# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wakelab < Formula
  desc "Wake and sleep your whole homelab from the CLI"
  homepage "https://github.com/DiegoHeer/wakelab"
  version "0.0.2"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DiegoHeer/wakelab/releases/download/v0.0.2/wakelab_0.0.2_darwin_amd64.tar.gz"
      sha256 "215b9d5e18094101cbd7a7f2db0c439072cbe9eb7de248e95070999746fcf40b"

      define_method(:install) do
        bin.install "wake"
        bash_completion.install "completions/wake.bash" => "wake"
        zsh_completion.install "completions/_wake"
        fish_completion.install "completions/wake.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DiegoHeer/wakelab/releases/download/v0.0.2/wakelab_0.0.2_darwin_arm64.tar.gz"
      sha256 "1fc4ce569191c74ba740c00bc337489b0dbfe91ea8e476826161e28f6a338fb5"

      define_method(:install) do
        bin.install "wake"
        bash_completion.install "completions/wake.bash" => "wake"
        zsh_completion.install "completions/_wake"
        fish_completion.install "completions/wake.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DiegoHeer/wakelab/releases/download/v0.0.2/wakelab_0.0.2_linux_amd64.tar.gz"
      sha256 "50bc630900da1fbb5316792c436bbd8d32216361aa5b9520edba4a796421f6bc"
      define_method(:install) do
        bin.install "wake"
        bash_completion.install "completions/wake.bash" => "wake"
        zsh_completion.install "completions/_wake"
        fish_completion.install "completions/wake.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DiegoHeer/wakelab/releases/download/v0.0.2/wakelab_0.0.2_linux_arm64.tar.gz"
      sha256 "cc717ce1cc03960500807bdbbcb7c42d3ca7f3150c861aa546adc5d8292efddb"
      define_method(:install) do
        bin.install "wake"
        bash_completion.install "completions/wake.bash" => "wake"
        zsh_completion.install "completions/_wake"
        fish_completion.install "completions/wake.fish"
      end
    end
  end

  test do
    assert_match "wake version", shell_output("#{bin}/wake --version")
  end
end
